import type { ObfuscateOptions } from "js-confuser";
import { type MinifyOptions } from "terser";

export const getMinifyOptions = (): MinifyOptions => {
    return {
        compress: {
            arrows: true,
            arguments: true,
            booleans: true,
            booleans_as_integers: true,
            collapse_vars: true,
            comparisons: true,
            computed_props: true,
            conditionals: true,
            dead_code: true,
            directives: true,
            drop_console: true,
            drop_debugger: true,
            ecma: 2020,
            evaluate: true,
            expression: true,
            hoist_funs: true,
            hoist_props: true,
            hoist_vars: true,
            if_return: true,
            inline: true,
            join_vars: true,
            keep_classnames: false,
            keep_fargs: false,
            keep_fnames: false,
            keep_infinity: false,
            loops: true,
            negate_iife: true,
            passes: 3,
            properties: true,
            pure_getters: "strict",
            reduce_funcs: true,
            reduce_vars: true,
            sequences: true,
            side_effects: true,
            switches: true,
            toplevel: true,
            typeofs: true,
            unsafe: true,
            unsafe_arrows: true,
            unsafe_comps: true,
            unsafe_Function: true,
            unsafe_math: true,
            unsafe_symbols: true,
            unsafe_methods: true,
            unsafe_proto: true,
            unsafe_regexp: true,
            unsafe_undefined: true,
            unused: true,
        },
        mangle: {
            eval: true,
            keep_classnames: false,
            keep_fnames: false,
            module: true,
            properties: {
                regex: /^[^_\.]/,
                reserved: [
                    "requestAnimFrame", "frvrSdkInitPromise", "FRVR", "bootstrapper", "complete", "tracker", "levelStart",
                    "ads", "show", "channelCharacteristics", "allowNavigation", "setChannel", "gameInit",

                    "Glotus", "id", "sid", "x", "y", "dir", "xWiggle", "yWiggle", "turnSpeed", "owner", "scale", "health",
                    "maxHealth", "isAI", "isPlayer", "index", "team", "checkTrusted",
                    "algorithm", "challenge", "number", "salt", "signature", "test", "took", "type", "payload", "start", "max",
                    "worker", "challengeData", "solution", "maxnumber", "obfuscated", "key", "teams", "primary", "secondary",
                    "wood", "food", "stone", "gold", "kills", "weaponIndex", "buildIndex",
                    "tailIndex", "skinIndex", "weaponVariant", "skinColor", "name", "moofoll", "skin", "method", "headers", "body", "Content-Type",
                    "DELTA", "LN1", "unsafeWindow", "GM_info", "GM_getValue", "GM_setValue", "GM_deleteValue", "processServers", "playerCapacity",
                    "customElements", "define",
                ]
            },
            toplevel: true
        },
        output: {
            beautify: false,
            braces: false,
            comments: false,
            ecma: 2020,
            indent_level: 0,
            indent_start: 0,
            inline_script: true,
            keep_numbers: false,
            keep_quoted_props: false,
            quote_keys: false,
            quote_style: 1,
            semicolons: true,
            shebang: false,
            webkit: false,
            wrap_iife: false,
            wrap_func_args: false
        },
        sourceMap: false,
        ecma: 2020,
        keep_classnames: false,
        keep_fnames: false,
        ie8: false,
        module: true,
        safari10: false,
        toplevel: true,
    }
}

export const getMinifyOptions2 = (): MinifyOptions => {
    return {
        compress: {
            arrows: true,
            arguments: true,
            booleans: true,
            booleans_as_integers: true,
            collapse_vars: true,
            comparisons: true,
            properties: false,
            computed_props: false,
            conditionals: true,
            dead_code: true,
            directives: true,
            drop_console: true,
            drop_debugger: true,
            ecma: 2020,
            evaluate: true,
            expression: true,
            hoist_funs: true,
            hoist_vars: true,
            if_return: true,
            inline: true,
            join_vars: true,
            keep_classnames: false,
            keep_fargs: false,
            keep_fnames: false,
            keep_infinity: false,
            loops: true,
            negate_iife: true,
            passes: 3,
            pure_getters: "strict",
            reduce_funcs: true,
            reduce_vars: true,
            sequences: true,
            side_effects: true,
            switches: true,
            toplevel: true,
            typeofs: true,
            unsafe: true,
            unsafe_arrows: true,
            unsafe_comps: true,
            unsafe_Function: true,
            unsafe_math: true,
            unsafe_regexp: true,
            unsafe_undefined: true,
            unsafe_methods: false,
            unsafe_proto: false,
            unsafe_symbols: false,
            unused: true,
        },

        mangle: {
            eval: true,
            keep_classnames: false,
            keep_fnames: false,
            module: true,
            properties: false,
            toplevel: true
        },

        output: {
            beautify: false,
            braces: false,
            comments: false,
            ecma: 2020,
            indent_level: 0,
            indent_start: 0,
            inline_script: true,
            keep_numbers: false,
            keep_quoted_props: true,
            quote_keys: false,
            quote_style: 1,
            semicolons: true,
            shebang: false,
            webkit: false,
            wrap_iife: false,
            wrap_func_args: false
        },

        sourceMap: false,
        ecma: 2020,
        keep_classnames: false,
        keep_fnames: false,
        ie8: false,
        module: true,
        safari10: false,
        toplevel: true,
    }
}

export const getSourceOptions = (): ObfuscateOptions => {
    return {
        target: "browser",
        calculator: 0.3,
        compact: true,
        globalConcealing: 0.9,
        identifierGenerator: "mangled",
        minify: true,
        movedDeclarations: 0.7,
        objectExtraction: 0.3,
        renameGlobals: true,
        shuffle: 0.3,
        stringConcealing: true,
        renameLabels: true,
        preserveFunctionLength: true,
        duplicateLiteralsRemoval: 0.3,
        stringSplitting: 0.3,
    }
}