import { EItem, EProjectile, EUpgradeType, EWeapon, ItemGroup, ItemType, WeaponType, WeaponVariant } from "../types/Items";

/**
 * Constant array of weapon data, index represent weapon ID
 */
export const Weapons = [{
    id: EWeapon.TOOL_HAMMER,
    itemType: WeaponType.PRIMARY,
    upgradeType: EUpgradeType.TOOL_HAMMER,
    type: 0,
    age: 0,
    name: "tool hammer",
    description: "tool for gathering all resources",
    src: "hammer_1",
    length: 140,
    width: 140,
    xOffset: -3,
    yOffset: 18,
    spdMult: 1,
    damage: 25,
    range: 65,
    gather: 1,
    speed: 300
}, {
    id: EWeapon.HAND_AXE,
    itemType: WeaponType.PRIMARY,
    upgradeType: EUpgradeType.AXE,
    type: 0,
    age: 2,
    name: "hand axe",
    description: "gathers resources at a higher rate",
    src: "axe_1",
    length: 140,
    width: 140,
    xOffset: 3,
    yOffset: 24,
    damage: 30,
    spdMult: 1,
    range: 70,
    gather: 2,
    speed: 400
}, {
    id: EWeapon.GREAT_AXE,
    itemType: WeaponType.PRIMARY,
    upgradeOf: EWeapon.HAND_AXE,
    upgradeType: EUpgradeType.AXE,
    type: 0,
    age: 8,
    pre: 1,
    name: "great axe",
    description: "deal more damage and gather more resources",
    src: "great_axe_1",
    length: 140,
    width: 140,
    xOffset: -8,
    yOffset: 25,
    damage: 35,
    spdMult: 1,
    range: 75,
    gather: 4,
    speed: 400
}, {
    id: EWeapon.SHORT_SWORD,
    itemType: WeaponType.PRIMARY,
    upgradeType: EUpgradeType.SWORD,
    type: 0,
    age: 2,
    name: "short sword",
    description: "increased attack power but slower move speed",
    src: "sword_1",
    iPad: 1.3,
    length: 130,
    width: 210,
    xOffset: -8,
    yOffset: 46,
    damage: 35,
    spdMult: .85,
    range: 110,
    gather: 1,
    speed: 300
}, {
    id: EWeapon.KATANA,
    itemType: WeaponType.PRIMARY,
    upgradeOf: EWeapon.SHORT_SWORD,
    upgradeType: EUpgradeType.SWORD,
    type: 0,
    age: 8,
    pre: 3,
    name: "katana",
    description: "greater range and damage",
    src: "samurai_1",
    iPad: 1.3,
    length: 130,
    width: 210,
    xOffset: -8,
    yOffset: 59,
    damage: 40,
    spdMult: .8,
    range: 118,
    gather: 1,
    speed: 300
}, {
    id: EWeapon.POLEARM,
    itemType: WeaponType.PRIMARY,
    upgradeType: EUpgradeType.POLEARM,
    isUpgrade: false,
    type: 0,
    age: 2,
    name: "polearm",
    description: "long range melee weapon",
    src: "spear_1",
    iPad: 1.3,
    length: 130,
    width: 210,
    xOffset: -8,
    yOffset: 53,
    damage: 45,
    knock: .2,
    spdMult: .82,
    range: 142,
    gather: 1,
    speed: 700
}, {
    id: EWeapon.BAT,
    itemType: WeaponType.PRIMARY,
    upgradeType: EUpgradeType.BAT,
    isUpgrade: false,
    type: 0,
    age: 2,
    name: "bat",
    description: "fast long range melee weapon",
    src: "bat_1",
    iPad: 1.3,
    length: 110,
    width: 180,
    xOffset: -8,
    yOffset: 53,
    damage: 20,
    knock: .7,
    spdMult: 1,
    range: 110,
    gather: 1,
    speed: 300
}, {
    id: EWeapon.DAGGERS,
    itemType: WeaponType.PRIMARY,
    upgradeType: EUpgradeType.DAGGERS,
    isUpgrade: false,
    type: 0,
    age: 2,
    name: "daggers",
    description: "really fast short range weapon",
    src: "dagger_1",
    iPad: .8,
    length: 110,
    width: 110,
    xOffset: 18,
    yOffset: 0,
    damage: 20,
    knock: .1,
    range: 65,
    gather: 1,
    hitSlow: .1,
    spdMult: 1.13,
    speed: 100
}, {
    id: EWeapon.STICK,
    itemType: WeaponType.PRIMARY,
    upgradeType: EUpgradeType.STICK,
    isUpgrade: false,
    type: 0,
    age: 2,
    name: "stick",
    description: "great for gathering but very weak",
    src: "stick_1",
    length: 140,
    width: 140,
    xOffset: 3,
    yOffset: 24,
    damage: 1,
    spdMult: 1,
    range: 70,
    gather: 7,
    speed: 400
}, {
    id: EWeapon.HUNTING_BOW,
    itemType: WeaponType.SECONDARY,
    upgradeType: EUpgradeType.BOW,
    projectile: EProjectile.BOW,
    type: 1,
    age: 6,
    name: "hunting bow",
    description: "bow used for ranged combat and hunting",
    src: "bow_1",
    cost: {
        food: 0,
        wood: 4,
        stone: 0,
        gold: 0,
    },
    length: 120,
    width: 120,
    xOffset: -6,
    yOffset: 0,
    spdMult: .75,
    speed: 600,
    range: 1000,
}, {
    id: EWeapon.GREAT_HAMMER,
    itemType: WeaponType.SECONDARY,
    upgradeType: EUpgradeType.GREAT_HAMMER,
    isUpgrade: false,
    type: 1,
    age: 6,
    name: "great hammer",
    description: "hammer used for destroying structures",
    src: "great_hammer_1",
    length: 140,
    width: 140,
    xOffset: -9,
    yOffset: 25,
    damage: 10,
    spdMult: .88,
    range: 75,
    sDmg: 7.5,
    gather: 1,
    speed: 400
}, {
    id: EWeapon.WOODEN_SHIELD,
    itemType: WeaponType.SECONDARY,
    upgradeType: EUpgradeType.WOODEN_SHIELD,
    isUpgrade: false,
    type: 1,
    age: 6,
    name: "wooden shield",
    description: "blocks projectiles and reduces melee damage",
    src: "shield_1",
    length: 120,
    width: 120,
    shield: .2,
    xOffset: 6,
    yOffset: 0,
    spdMult: .7,
    speed: 1,
    range: 0,
}, {
    id: EWeapon.CROSSBOW,
    itemType: WeaponType.SECONDARY,
    upgradeType: EUpgradeType.BOW,
    projectile: EProjectile.CROSSBOW,
    upgradeOf: EWeapon.HUNTING_BOW,
    type: 1,
    age: 8,
    pre: 9,
    name: "crossbow",
    description: "deals more damage and has greater range",
    src: "crossbow_1",
    cost: {
        food: 0,
        wood: 5,
        stone: 0,
        gold: 0,
    },
    aboveHand: true,
    armS: .75,
    length: 120,
    width: 120,
    xOffset: -4,
    yOffset: 0,
    spdMult: .7,
    speed: 700,
    range: 1200,
}, {
    id: EWeapon.REPEATER_CROSSBOW,
    itemType: WeaponType.SECONDARY,
    upgradeType: EUpgradeType.BOW,
    projectile: EProjectile.REPEATER,
    upgradeOf: EWeapon.CROSSBOW,
    type: 1,
    age: 9,
    pre: 12,
    name: "repeater crossbow",
    description: "high firerate crossbow with reduced damage",
    src: "crossbow_2",
    cost: {
        food: 0,
        wood: 10,
        stone: 0,
        gold: 0,
    },
    aboveHand: true,
    armS: .75,
    length: 120,
    width: 120,
    xOffset: -4,
    yOffset: 0,
    spdMult: .7,
    speed: 230,
    range: 1200,
}, {
    id: EWeapon.MC_GRABBY,
    itemType: WeaponType.SECONDARY,
    upgradeType: EUpgradeType.MC_GRABBY,
    isUpgrade: false,
    type: 1,
    age: 6,
    name: "mc grabby",
    description: "steals resources from enemies",
    src: "grab_1",
    length: 130,
    width: 210,
    xOffset: -8,
    yOffset: 53,
    damage: 0,
    steal: 250,
    knock: .2,
    spdMult: 1.05,
    range: 125,
    gather: 0,
    speed: 700
}, {
    id: EWeapon.MUSKET,
    itemType: WeaponType.SECONDARY,
    upgradeType: EUpgradeType.BOW,
    projectile: EProjectile.MUSKET,
    upgradeOf: EWeapon.CROSSBOW,
    type: 1,
    age: 9,
    pre: 12,
    name: "musket",
    description: "slow firerate but high damage and range",
    src: "musket_1",
    cost: {
        food: 0,
        wood: 0,
        stone: 10,
        gold: 0,
    },
    aboveHand: true,
    rec: .35,
    armS: .6,
    hndS: .3,
    hndD: 1.6,
    length: 205,
    width: 205,
    xOffset: 25,
    yOffset: 0,
    hideProjectile: true,
    spdMult: .6,
    speed: 1500,
    range: 1400,
}] as const;

/**
 * All existing item groups. Each group have unique layer and max placement count
 */
export const ItemGroups = {
    [ItemGroup.WALL]: {
        name: "Wall",
        limit: 30,
        layer: 0,
    },
    [ItemGroup.SPIKE]: {
        name: "Spike",
        limit: 15,
        layer: 0,
    },
    [ItemGroup.WINDMILL]: {
        name: "Windmill",
        limit: 7,
        sandboxLimit: 299,
        layer: 1,
    },
    [ItemGroup.MINE]: {
        name: "Mine",
        limit: 1,
        layer: 0,
    },
    [ItemGroup.TRAP]: {
        name: "Trap",
        limit: 6,
        layer: -1,
    },
    [ItemGroup.BOOST]: {
        name: "Boost",
        limit: 12,
        sandboxLimit: 299,
        layer: -1,
    },
    [ItemGroup.TURRET]: {
        name: "Turret",
        limit: 2,
        layer: 1,
    },
    [ItemGroup.PLATFORM]: {
        name: "Plaftorm",
        limit: 12,
        layer: -1,
    },
    [ItemGroup.HEAL_PAD]: {
        name: "Healing pad",
        limit: 4,
        layer: -1,
    },
    [ItemGroup.SPAWN]: {
        name: "Spawn",
        limit: 1,
        layer: -1,
    },
    [ItemGroup.SAPLING]: {
        name: "Sapling",
        limit: 2,
        layer: 0,
    },
    [ItemGroup.BLOCKER]: {
        name: "Blocker",
        limit: 3,
        layer: -1,
    },
    [ItemGroup.TELEPORTER]: {
        name: "Teleporter",
        limit: 2,
        sandboxLimit: 299,
        layer: -1,
    },
} as const;

/**
 * Constant array of items. Food and items are combined together
 */
export const Items = [{
    id: EItem.APPLE,
    itemType: ItemType.FOOD,
    name: "apple",
    description: "restores 20 health when consumed",
    age: 0,
    cost: {
        food: 10,
        wood: 0,
        stone: 0,
        gold: 0,
    },
    restore: 20,
    scale: 22,
    holdOffset: 15
}, {
    id: EItem.COOKIE,
    itemType: ItemType.FOOD,
    upgradeOf: EItem.APPLE,
    name: "cookie",
    description: "restores 40 health when consumed",
    age: 3,
    cost: {
        food: 15,
        wood: 0,
        stone: 0,
        gold: 0,
    },
    restore: 40,
    scale: 27,
    holdOffset: 15
}, {
    id: EItem.CHEESE,
    itemType: ItemType.FOOD,
    upgradeOf: EItem.COOKIE,
    name: "cheese",
    description: "restores 30 health and another 50 over 5 seconds",
    age: 7,
    cost: {
        food: 25,
        wood: 0,
        stone: 0,
        gold: 0,
    },
    restore: 30,
    scale: 27,
    holdOffset: 15
}, {
    id: EItem.WOOD_WALL,
    itemType: ItemType.WALL,
    itemGroup: ItemGroup.WALL,
    name: "wood wall",
    description: "provides protection for your village",
    age: 0,
    cost: {
        food: 0,
        wood: 10,
        stone: 0,
        gold: 0,
    },
    projDmg: true,
    health: 380,
    scale: 50,
    holdOffset: 20,
    placeOffset: -5
}, {
    id: EItem.STONE_WALL,
    itemType: ItemType.WALL,
    itemGroup: ItemGroup.WALL,
    upgradeOf: EItem.WOOD_WALL,
    name: "stone wall",
    description: "provides improved protection for your village",
    age: 3,
    cost: {
        food: 0,
        wood: 0,
        stone: 25,
        gold: 0,
    },
    health: 900,
    scale: 50,
    holdOffset: 20,
    placeOffset: -5
}, {
    pre: 1,
    id: EItem.CASTLE_WALL,
    itemType: ItemType.WALL,
    itemGroup: ItemGroup.WALL,
    upgradeOf: EItem.STONE_WALL,
    name: "castle wall",
    description: "provides powerful protection for your village",
    age: 7,
    cost: {
        food: 0,
        wood: 0,
        stone: 35,
        gold: 0,
    },
    health: 1500,
    scale: 52,
    holdOffset: 20,
    placeOffset: -5
}, {
    id: EItem.SPIKES,
    itemType: ItemType.SPIKE,
    itemGroup: ItemGroup.SPIKE,
    name: "spikes",
    description: "damages enemies when they touch them",
    age: 0,
    cost: {
        food: 0,
        wood: 20,
        stone: 5,
        gold: 0,
    },
    health: 400,
    damage: 20,
    scale: 49,
    spritePadding: -23,
    holdOffset: 8,
    placeOffset: -5
}, {
    id: EItem.GREATER_SPIKES,
    itemType: ItemType.SPIKE,
    itemGroup: ItemGroup.SPIKE,
    upgradeOf: EItem.SPIKES,
    name: "greater spikes",
    description: "damages enemies when they touch them",
    age: 5,
    cost: {
        food: 0,
        wood: 30,
        stone: 10,
        gold: 0,
    },
    health: 500,
    damage: 35,
    scale: 52,
    spritePadding: -23,
    holdOffset: 8,
    placeOffset: -5
}, {
    id: EItem.POISON_SPIKES,
    itemType: ItemType.SPIKE,
    itemGroup: ItemGroup.SPIKE,
    upgradeOf: EItem.GREATER_SPIKES,
    name: "poison spikes",
    description: "poisons enemies when they touch them",
    age: 9,
    pre: 1,
    cost: {
        food: 0,
        wood: 35,
        stone: 15,
        gold: 0,
    },
    health: 600,
    damage: 30,
    poisonDamage: 5,
    scale: 52,
    spritePadding: -23,
    holdOffset: 8,
    placeOffset: -5
}, {
    id: EItem.SPINNING_SPIKES,
    itemType: ItemType.SPIKE,
    itemGroup: ItemGroup.SPIKE,
    upgradeOf: EItem.GREATER_SPIKES,
    name: "spinning spikes",
    description: "damages enemies when they touch them",
    age: 9,
    pre: 2,
    cost: {
        food: 0,
        wood: 30,
        stone: 20,
        gold: 0,
    },
    health: 500,
    damage: 45,
    turnSpeed: .003,
    scale: 52,
    spritePadding: -23,
    holdOffset: 8,
    placeOffset: -5
}, {
    id: EItem.WINDMILL,
    itemType: ItemType.WINDMILL,
    itemGroup: ItemGroup.WINDMILL,
    name: "windmill",
    description: "generates gold over time",
    age: 0,
    cost: {
        food: 0,
        wood: 50,
        stone: 10,
        gold: 0,
    },
    health: 400,
    pps: 1,
    turnSpeed: .0016,
    spritePadding: 25,
    iconLineMult: 12,
    scale: 45,
    holdOffset: 20,
    placeOffset: 5
}, {
    id: EItem.FASTER_WINDMILL,
    itemType: ItemType.WINDMILL,
    itemGroup: ItemGroup.WINDMILL,
    upgradeOf: EItem.WINDMILL,
    name: "faster windmill",
    description: "generates more gold over time",
    age: 5,
    pre: 1,
    cost: {
        food: 0,
        wood: 60,
        stone: 20,
        gold: 0,
    },
    health: 500,
    pps: 1.5,
    turnSpeed: .0025,
    spritePadding: 25,
    iconLineMult: 12,
    scale: 47,
    holdOffset: 20,
    placeOffset: 5
}, {
    id: EItem.POWER_MILL,
    itemType: ItemType.WINDMILL,
    itemGroup: ItemGroup.WINDMILL,
    upgradeOf: EItem.FASTER_WINDMILL,
    name: "power mill",
    description: "generates more gold over time",
    age: 8,
    pre: 1,
    cost: {
        food: 0,
        wood: 100,
        stone: 50,
        gold: 0,
    },
    health: 800,
    pps: 2,
    turnSpeed: .005,
    spritePadding: 25,
    iconLineMult: 12,
    scale: 47,
    holdOffset: 20,
    placeOffset: 5
}, {
    id: EItem.MINE,
    itemType: ItemType.FARM,
    itemGroup: ItemGroup.MINE,
    name: "mine",
    description: "allows you to mine stone",
    age: 5,
    type: 2,
    cost: {
        food: 0,
        wood: 20,
        stone: 100,
        gold: 0,
    },
    iconLineMult: 12,
    scale: 65,
    holdOffset: 20,
    placeOffset: 0
}, {
    id: EItem.SAPLING,
    itemType: ItemType.FARM,
    itemGroup: ItemGroup.SAPLING,
    name: "sapling",
    description: "allows you to farm wood",
    age: 5,
    type: 0,
    cost: {
        food: 0,
        wood: 150,
        stone: 0,
        gold: 0,
    },
    iconLineMult: 12,
    colDiv: .5,
    scale: 110,
    holdOffset: 50,
    placeOffset: -15
}, {
    id: EItem.PIT_TRAP,
    itemType: ItemType.TRAP,
    itemGroup: ItemGroup.TRAP,
    name: "pit trap",
    description: "pit that traps enemies if they walk over it",
    age: 4,
    cost: {
        food: 0,
        wood: 30,
        stone: 30,
        gold: 0,
    },
    trap: true,
    ignoreCollision: true,
    hideFromEnemy: true,
    health: 500,
    colDiv: .2,
    scale: 50,
    holdOffset: 20,
    placeOffset: -5
}, {
    id: EItem.BOOST_PAD,
    itemType: ItemType.TRAP,
    itemGroup: ItemGroup.BOOST,
    name: "boost pad",
    description: "provides boost when stepped on",
    age: 4,
    cost: {
        food: 0,
        wood: 5,
        stone: 20,
        gold: 0,
    },
    ignoreCollision: true,
    boostSpeed: 1.5,
    health: 150,
    colDiv: .7,
    scale: 45,
    holdOffset: 20,
    placeOffset: -5
}, {
    id: EItem.TURRET,
    itemType: ItemType.TURRET,
    itemGroup: ItemGroup.TURRET,
    name: "turret",
    description: "defensive structure that shoots at enemies",
    age: 7,
    doUpdate: true,
    cost: {
        food: 0,
        wood: 200,
        stone: 150,
        gold: 0,
    },
    health: 800,
    projectile: 1,
    shootRange: 700,
    shootRate: 2200,
    scale: 43,
    holdOffset: 20,
    placeOffset: -5
}, {
    id: EItem.PLATFORM,
    itemType: ItemType.TURRET,
    itemGroup: ItemGroup.PLATFORM,
    name: "platform",
    description: "platform to shoot over walls and cross over water",
    age: 7,
    cost: {
        food: 0,
        wood: 20,
        stone: 0,
        gold: 0,
    },
    ignoreCollision: true,
    zIndex: 1,
    health: 300,
    scale: 43,
    holdOffset: 20,
    placeOffset: -5
}, {
    id: EItem.HEALING_PAD,
    itemType: ItemType.TURRET,
    itemGroup: ItemGroup.HEAL_PAD,
    name: "healing pad",
    description: "standing on it will slowly heal you",
    age: 7,
    cost: {
        food: 10,
        wood: 30,
        stone: 0,
        gold: 0,
    },
    ignoreCollision: true,
    healCol: 15,
    health: 400,
    colDiv: .7,
    scale: 45,
    holdOffset: 20,
    placeOffset: -5
}, {
    id: EItem.SPAWN_PAD,
    itemType: ItemType.SPAWN,
    itemGroup: ItemGroup.SPAWN,
    name: "spawn pad",
    description: "you will spawn here when you die but it will dissapear",
    age: 9,
    cost: {
        food: 0,
        wood: 100,
        stone: 100,
        gold: 0,
    },
    health: 400,
    ignoreCollision: true,
    spawnPoint: true,
    scale: 45,
    holdOffset: 20,
    placeOffset: -5
}, {
    id: EItem.BLOCKER,
    itemType: ItemType.TURRET,
    itemGroup: ItemGroup.BLOCKER,
    name: "blocker",
    description: "blocks building in radius",
    age: 7,
    cost: {
        food: 0,
        wood: 30,
        stone: 25,
        gold: 0,
    },
    ignoreCollision: true,
    blocker: 300,
    health: 400,
    colDiv: .7,
    scale: 45,
    holdOffset: 20,
    placeOffset: -5
}, {
    id: EItem.TELEPORTER,
    itemType: ItemType.TURRET,
    itemGroup: ItemGroup.TELEPORTER,
    name: "teleporter",
    description: "teleports you to a random point on the map",
    age: 7,
    cost: {
        food: 0,
        wood: 60,
        stone: 60,
        gold: 0,
    },
    ignoreCollision: true,
    teleport: true,
    health: 200,
    colDiv: .7,
    scale: 45,
    holdOffset: 20,
    placeOffset: -5
}] as const;

// const data = {} as any;
// for (const item of Items) {
//     const offset = "scale" in item ? item.scale : 0;
//     if (data[offset] === undefined) {
//         data[offset] = [];
//     }
//     data[offset].push(item.name);
// }
// console.log(data);

/**
 * All existing weapon variants
 */
export const WeaponVariants = [{
    id: WeaponVariant.STONE,
    src: "",
    xp: 1,
    needXP: 0,
    val: 1,
    color: "#7e7e90",
}, {
    id: WeaponVariant.GOLD,
    src: "_g",
    xp: 3000,
    needXP: 3000,
    val: 1.1,
    color: "#f7cf45",
}, {
    id: WeaponVariant.DIAMOND,
    src: "_d",
    xp: 7000,
    needXP: 4000,
    val: 1.18,
    color: "#6d91cb",
}, {
    id: WeaponVariant.RUBY,
    src: "_r",
    poison: true,
    xp: 12000,
    needXP: 5000,
    val: 1.18,
    color: "#be5454",
}] as const;

/**
 * All existing projectiles for shooting weapons and turrets
 */
export const Projectiles = [{
    id: EProjectile.BOW,
    name: "Hunting bow",
    index: 0,
    layer: 0,
    src: "arrow_1",
    damage: 25,
    scale: 103,
    range: 1000,
    speed: 1.6,
}, {
    id: EProjectile.TURRET,
    name: "Turret",
    index: 1,
    layer: 1,
    damage: 25,
    scale: 20,
    speed: 1.5,
    range: 700
}, {
    id: EProjectile.CROSSBOW,
    name: "Crossbow",
    index: 0,
    layer: 0,
    src: "arrow_1",
    damage: 35,
    scale: 103,
    range: 1200,
    speed: 2.5,
}, {
    id: EProjectile.REPEATER,
    name: "Repeater crossbow",
    index: 0,
    layer: 0,
    src: "arrow_1",
    damage: 30,
    scale: 103,
    range: 1200,
    speed: 2,
}, {
    id: EProjectile.UNKNOWN,
    index: 1,
    layer: 1,
    damage: 16,
    scale: 20,
    range: 0,
    speed: 0
}, {
    id: EProjectile.MUSKET,
    name: "Musket",
    index: 0,
    layer: 0,
    src: "bullet_1",
    damage: 50,
    scale: 160,
    range: 1400,
    speed: 3.6,
}] as const;