export const enum SocketServer {
    CONNECTION_ESTABLISHED   = "io-init",
    CLAN_INFO_INIT           = "A",
    DISCONNECT               = "B",
    MY_PLAYER_SPAWN          = "C",
    CREATE_PLAYER            = "D",
    REMOVE_PLAYER            = "E",
    MOVE_UPDATE              = "a",
    UPDATE_LEADERBOARD       = "G",
    ADD_OBJECT               = "H",
    LOAD_AI                  = "I",
    ANIMATE_AI               = "J",
    ATTACK_ANIMATION         = "K",
    HIT_OBJECT               = "L",
    SHOOT_TURRET             = "M",
    UPDATE_RESOURCES         = "N",
    UPDATE_PLAYER_HEALTH     = "O",
    MY_PLAYER_DEATH          = "P",
    REMOVE_OBJECT            = "Q",
    REMOVE_ALL_OBJECTS       = "R",
    ITEM_COUNT               = "S",
    UPDATE_AGE               = "T",
    NEW_UPGRADE              = "U",
    UPDATE_ITEMS             = "V",
    CREATE_PROJECTILE        = "X",
    REMOVE_PROJECTILE        = "Y",
    SHUTDOWN_SERVER          = "Z",
    ADD_ALLIANCE             = "g",
    REMOVE_ALLIANCE          = "1",
    PLAYER_CLAN_JOIN_REQUEST = "2",
    UPDATE_MY_CLAN           = "3",
    UPDATE_CLAN_MEMBERS      = "4",
    UPDATE_STORE             = "5",
    RECEIVE_CHAT             = "6",
    UPDATE_MINIMAP           = "7",
    SHOW_TEXT                = "8",
    PING_MAP                 = "9",
    PING_RESPONSE            = "0",

    CLAN_CREATED             = "g",
    CLAN_DELETED             = "1",
}

export const enum SocketClient { 
    ACCEPT_CLAN_JOIN_REQUEST = "P",
    KICK_FROM_CLAN           = "Q",
    JOIN_CLAN                = "b",
    CREATE_CLAN              = "L",
    LEAVE_CLAN               = "N",
    STORE                    = "c",
    CHAT                     = "6",
    RESET_MOVE_DIR           = "e",
    ATTACK                   = "F",
    MOVE                     = "9",
    PLAYER_CONTROL           = "K",
    PING_MAP                 = "S",
    SELECT_ITEM              = "z",
    SPAWN                    = "M",
    UPGRADE_ITEM             = "H",
    ANGLE                    = "D",
    PING_REQUEST             = "0",
}

export interface IEncoder {
    Encoder: { readonly encode: ((data: any) => Uint8Array) } | null;
    Decoder: { readonly decode: ((data: Uint8Array) => any) } | null;
}