import { EAccessory, EHat } from "../types/Store";
import CustomStorage from "./CustomStorage";

export const defaultSettings = {
    _primary: "Digit1",
    _secondary: "Digit2",
    _food: "KeyQ",
    _wall: "Digit4",
    _spike: "KeyC",
    _windmill: "KeyR",
    _farm: "KeyT",
    _trap: "Space",
    _turret: "KeyF",
    _spawn: "KeyG",
    _up: "KeyW",
    _left: "KeyA",
    _down: "KeyS",
    _right: "KeyD",
    _autoattack: "KeyE",
    _lockrotation: "KeyX",
    _lockBotPosition: "KeyZ",
    _toggleChat: "Enter",
    _toggleShop: "ShiftLeft",
    _toggleClan: "ControlLeft",
    _toggleMenu: "Escape",
    _biomehats: true,
    _autoemp: true,
    _antienemy: true,
    _antianimal: true,
    _antispike: true,
    _autoheal: true,
    _autoSync: true,
    _velocityTick: true,
    _spikeSyncHammer: true,
    _spikeSync: true,
    _spikeTick: true,
    _knockbackTickTrap: true,
    _knockbackTickHammer: true,
    _knockbackTick: true,
    _kbDefense: true,
    _automill: true,
    _autoplacer: true,
    _autobreak: true,
    _safeWalk: true,
    _autoGrind: true,
    _enemyTracers: false,
    _enemyTracersColor: "#cc5151",
    _teammateTracers: false,
    _teammateTracersColor: "#8ecc51",
    _animalTracers: false,
    _animalTracersColor: "#518ccc",
    _notificationTracers: true,
    _notificationTracersColor: "#f5d951",
    _arrows: true,
    _itemMarkers: true,
    _itemMarkersColor: "#84bd4b",
    _teammateMarkers: true,
    _teammateMarkersColor: "#bdb14b",
    _enemyMarkers: true,
    _enemyMarkersColor: "#ba4949",
    _weaponXPBar: true,
    _playerTurretReloadBar: true,
    _playerTurretReloadBarColor: "#cf7148",
    _weaponReloadBar: true,
    _weaponReloadBarColor: "#5155cc",
    _renderHP: true,
    _objectTurretReloadBar: false,
    _objectTurretReloadBarColor: "#66d9af",
    _itemHealthBar: false,
    _itemHealthBarColor: "#6b449e",
    _itemCounter: true,
    _renderGrid: false,
    _windmillRotation: false,
    _entityDanger: true,
    _displayPlayerAngle: false,
    _projectileHitbox: false,
    _possibleShootTarget: false,
    _weaponHitbox: false,
    _collisionHitbox: false,
    _placementHitbox: false,
    _turretHitbox: false,
    _possiblePlacement: true,
    _autospawn: false,
    _autoaccept: false,
    _menuTransparency: false,
    _followCursor: true,
    _storeItems: [[
        EHat.WINTER_CAP,
        EHat.FLIPPER_HAT,
        EHat.SOLDIER_HELMET,
        EHat.BULL_HELMET,
        EHat.EMP_HELMET,
        EHat.BOOSTER_HAT,
        EHat.BARBARIAN_ARMOR,
        EHat.SPIKE_GEAR,
        EHat.TURRET_GEAR,
        EHat.SAMURAI_ARMOR,
        EHat.TANK_GEAR,
        EHat.ASSASSIN_GEAR
    ], [
        EAccessory.MONKEY_TAIL,
        EAccessory.APPLE_BASKET,
        EAccessory.SAWBLADE,
        EAccessory.ANGEL_WINGS,
        EAccessory.SHADOW_WINGS,
        EAccessory.BLOOD_WINGS,
        EAccessory.CORRUPT_X_WINGS,
    ]],
};

export type ISettings = typeof defaultSettings;
const settings = { ...defaultSettings, ...CustomStorage.get<ISettings>("Glotus") };
for (const iterator in settings) {
    const key = iterator as keyof ISettings;
    if (!defaultSettings.hasOwnProperty(key)) {
        delete settings[key];
    }
}

export const SaveSettings = () => {
    CustomStorage.set("Glotus", settings);
}
SaveSettings();

export default settings;